GUILD_ID = 676183052543590420
overwatch_role = 1015277487112081420
movie_role = 980277929504284672
m_plus_role = 948681679701147649
pvp_role = 892432571814785063
colorado_role = 1030970627634511892
mightcon_role = 987514971481059418
ready_to_raid_role = 787441363222396928
guild_member_role = 676185937323229189
raid_friends_role = 923372461293199400

blacklisted_users = [
    312278335260721163,
]

kat_gif_list = [
    "https://tenor.com/view/eye-squint-markiplier-glare-suspicious-gif-15742154",
    "https://tenor.com/view/really-what-squint-chicken-gif-15168180",
    "https://tenor.com/view/skeptical-futurama-fry-hmmm-i-got-my-eyes-on-you-gif-17101711",
    "https://tenor.com/view/buffy-the-vampire-slayer-eye-gif-26036478",
    "https://tenor.com/view/dog-suspicious-suspicious-dog-squinting-squint-chihuahua-squint-gif-26088382",
    "https://tenor.com/view/pusheen-pusheen-cat-cat-cartoon-cute-gif-25196813"
]

enchant_map = {
    6572: "Enchant Bracers - Devotion of Avoidance",
    6573: "Enchant Bracers - Devotion of Avoidance",
    6574: "Enchant Bracers - Devotion of Avoidance",
    6578: "Enchant Bracers - Devotion of Leech",
    6579: "Enchant Bracers - Devotion of Leech",
    6580: "Enchant Bracers - Devotion of Leech",
    6584: "Enchant Bracers - Devotion of Speed",
    6585: "Enchant Bracers - Devotion of Speed",
    6586: "Enchant Bracers - Devotion of Speed",
    6569: "Enchant Bracers - Writ of Avoidance",
    6570: "Enchant Bracers - Writ of Avoidance",
    6571: "Enchant Bracers - Writ of Avoidance",
    6575: "Enchant Bracers - Writ of Leech",
    6576: "Enchant Bracers - Writ of Leech",
    6577: "Enchant Bracers - Writ of Leech",
    6581: "Enchant Bracers - Writ of Speed",
    6582: "Enchant Bracers - Writ of Speed",
    6583: "Enchant Bracers - Writ of Speed",
    6629: "Enchant Weapon - Burning Devotion",
    6630: "Enchant Weapon - Burning Devotion",
    6631: "Enchant Weapon - Burning Devotion",
    6626: "Enchant Weapon - Burning Writ",
    6627: "Enchant Weapon - Burning Writ",
    6628: "Enchant Weapon - Burning Writ",
    6635: "Enchant Weapon - Earthen Devotion",
    6636: "Enchant Weapon - Earthen Devotion",
    6637: "Enchant Weapon - Earthen Devotion",
    6632: "Enchant Weapon - Earthen Writ",
    6633: "Enchant Weapon - Earthen Writ",
    6634: "Enchant Weapon - Earthen Writ",
    6647: "Enchant Weapon - Frozen Devotion",
    6648: "Enchant Weapon - Frozen Devotion",
    6649: "Enchant Weapon - Frozen Devotion",
    6644: "Enchant Weapon - Frozen Writ",
    6645: "Enchant Weapon - Frozen Writ",
    6646: "Enchant Weapon - Frozen Writ",
    6641: "Enchant Weapon - Sophic Devotion",
    6642: "Enchant Weapon - Sophic Devotion",
    6643: "Enchant Weapon - Sophic Devotion",
    6638: "Enchant Weapon - Sophic Writ",
    6639: "Enchant Weapon - Sophic Writ",
    6640: "Enchant Weapon - Sophic Writ",
    6653: "Enchant Weapon - Wafting Devotion",
    6654: "Enchant Weapon - Wafting Devotion",
    6655: "Enchant Weapon - Wafting Devotion",
    6650: "Enchant Weapon - Wafting Writ",
    6651: "Enchant Weapon - Wafting Writ",
    6652: "Enchant Weapon - Wafting Writ",
    6617: "Enchant Chest - Reserve of Intellect",
    6618: "Enchant Chest - Reserve of Intellect",
    6619: "Enchant Chest - Reserve of Intellect",
    6623: "Enchant Chest - Waking Stats",
    6624: "Enchant Chest - Waking Stats",
    6625: "Enchant Chest - Waking Stats",
    6614: "Enchant Chest - Accelerated Agility",
    6615: "Enchant Chest - Accelerated Agility",
    6616: "Enchant Chest - Accelerated Agility",
    6620: "Enchant Chest - Sustained Strength",
    6621: "Enchant Chest - Sustained Strength",
    6622: "Enchant Chest - Sustained Strength",
    6548: "Enchant Ring - Devotion of Critical Strike",
    6549: "Enchant Ring - Devotion of Critical Strike",
    6550: "Enchant Ring - Devotion of Critical Strike",
    6566: "Enchant Ring - Devotion of Versatility",
    6567: "Enchant Ring - Devotion of Versatility",
    6568: "Enchant Ring - Devotion of Versatility",
    6545: "Enchant Ring - Writ of Critical Strike",
    6546: "Enchant Ring - Writ of Critical Strike",
    6547: "Enchant Ring - Writ of Critical Strike",
    6551: "Enchant Ring - Writ of Haste",
    6552: "Enchant Ring - Writ of Haste",
    6553: "Enchant Ring - Writ of Haste",
    6554: "Enchant Ring - Devotion of Haste",
    6555: "Enchant Ring - Devotion of Haste",
    6556: "Enchant Ring - Devotion of Haste",
    6557: "Enchant Ring - Writ of Mastery",
    6558: "Enchant Ring - Writ of Mastery",
    6559: "Enchant Ring - Writ of Mastery",
    6560: "Enchant Ring - Devotion of Mastery",
    6561: "Enchant Ring - Devotion of Mastery",
    6562: "Enchant Ring - Devotion of Mastery",
    6563: "Enchant Ring - Writ of Versatility",
    6564: "Enchant Ring - Writ of Versatility",
    6565: "Enchant Ring - Writ of Versatility",
    6590: "Enchant Cloak - Graceful Avoidance",
    6591: "Enchant Cloak - Graceful Avoidance",
    6592: "Enchant Cloak - Graceful Avoidance",
    6587: "Enchant Cloak - Writ of Avoidance",
    6588: "Enchant Cloak - Writ of Avoidance",
    6589: "Enchant Cloak - Writ of Avoidance",
    6596: "Enchant Cloak - Regenerative Leech",
    6597: "Enchant Cloak - Regenerative Leech",
    6598: "Enchant Cloak - Regenerative Leech",
    6602: "Enchant Cloak - Homebound Speed",
    6603: "Enchant Cloak - Homebound Speed",
    6604: "Enchant Cloak - Homebound Speed",
    6599: "Enchant Cloak - Writ of Speed",
    6600: "Enchant Cloak - Writ of Speed",
    6601: "Enchant Cloak - Writ of Speed",
    6593: "Enchant Cloak - Writ of Leech",
    6594: "Enchant Cloak - Writ of Leech",
    6595: "Enchant Cloak - Writ of Leech",
    6611: "Enchant Boots - Watcher's Loam",
    6612: "Enchant Boots - Watcher's Loam",
    6613: "Enchant Boots - Watcher's Loam",
    6605: "Enchant Boots - Plainsrunner's Breeze",
    6606: "Enchant Boots - Plainsrunner's Breeze",
    6607: "Enchant Boots - Plainsrunner's Breeze",
    6608: "Enchant Boots - Rider's Reassurance",
    6609: "Enchant Boots - Rider's Reassurance",
    6610: "Enchant Boots - Rider's Reassurance",
    6536: "Vibrant Spellthread",
    6537: "Vibrant Spellthread",
    6538: "Vibrant Spellthread",
    6539: "Frozen Spellthread",
    6540: "Frozen Spellthread",
    6541: "Frozen Spellthread",
    6542: "Temporal Spellthread",
    6543: "Temporal Spellthread",
    6544: "Temporal Spellthread",
    6488: "Fierce Armor Kit",
    6489: "Fierce Armor Kit",
    6450: "Fierce Armor Kit",
    6491: "Reinforced Armor Kit",
    6492: "Reinforced Armor Kit",
    6493: "Reinforced Armor Kit",
    6494: "Frosted Armor Kit",
    6495: "Frosted Armor Kit",
    6496: "Frosted Armor Kit",
}

class_role_dict = {
    "Death Knight": 1062137979314905179,
    "Demon Hunter": 1062138171242070036,
    "Druid": 1062138176216506448,
    "Evoker": 1062138178749857792,
    "Hunter": 1062138181513920512,
    "Mage": 1062138229207339058,
    "Monk": 1062138232256602302,
    "Paladin": 1062138234416676874,
    "Priest": 1062138236811608095,
    "Rogue": 1062138238938132511,
    "Shaman": 1062138241404383292,
    "Warlock": 1062138250325659658,
    "Warrior": 1062138252884189326
}

wow_spec_dict = {
    "Death Knight": {
        "a Blood": [0xC41E3A, 'Tank',
                    'A dark guardian who manipulates and corrupts life energy to sustain <him/her>self in the face of an enemy onslaught.',
                    'Spell_deathknight_bloodpresence.png'],
        "a Frost": [0xC41E3A, 'Melee DPS',
                    'An icy harbinger of doom, channeling runic power and delivering vicious weapon strikes.',
                    'Spell_deathknight_frostpresence.png'],
        "an Unholy": [0xC41E3A, 'Melee DPS',
                      'A master of death and decay, spreading infection and controlling undead minions to do <his/her> bidding.',
                      'Spell_deathknight_unholypresence.png']
    },
    "Demon Hunter": {
        "a Vengeance": [0xA330C9, 'Tank', 'Embraces the demon within to incinerate enemies and protect their allies.',
                        'Demon_hunter_vengeance_icon.png'],
        "a Havoc": [0xA330C9, 'Melee DPS', 'A brooding master of warglaives and the destructive power of fel magic.',
                    'Demon_hunter_havoc_icon.png']
    },
    "Druid": {
        "a Guardian": [0xFF7C0A, 'Tank', 'Takes on the form of a mighty bear to absorb damage and protect allies.',
                       'Ability_racial_bearform.png'],
        "a Feral": [0xFF7C0A, 'Melee DPS', 'Takes on the form of a great cat to deal damage with bleeds and bites.',
                    'Ability_druid_catform.png'],
        "a Balance": [0xFF7C0A, 'Ranged DPS',
                      'Can take on the form of a powerful Moonkin, balancing the power of Arcane and Nature magic to destroy enemies at a distance.',
                      'Spell_nature_starfall.png'],
        "a Restoration": [0xFF7C0A, 'Healer', 'Uses heal-over-time Nature spells to keep allies alive.',
                          'Spell_nature_healingtouch.png']
    },
    "Evoker": {
        "a Devastation": [0x33937F, 'Ranged DPS',
                          'A ranged DPS specialization that mainly focuses on the magic of the red and blue dragonflights to harm foes from a distance with a variety of concentrated spells and powerful breath attacks.',
                          'https://upload.wikimedia.org/wikipedia/en/5/53/Spyro.png'],
        "a Preservation": [0x33937F, 'Healer',
                           'A healer specialization that largely utilizes the magic of the green and bronze dragonflights to heal allies with breaths and even rewind time on wounds themselves!',
                           'https://upload.wikimedia.org/wikipedia/en/5/53/Spyro.png'],
    },
    "Hunter": {
        "a Beast Mastery": [0xAAD372, 'Ranged DPS',
                            'A master of the wild who can tame a wide variety of beasts to assist <him/her> in combat.',
                            'Ability_hunter_bestialdiscipline.png'],
        "a Marksmanship": [0xAAD372, 'Ranged DPS',
                           'A master archer or sharpshooter who excels in bringing down enemies from afar.',
                           'Ability_hunter_focusedaim.png'],
        "a Survival": [0xAAD372, 'Melee DPS',
                       'A rugged tracker who favors using animal venom, explosives and traps as deadly weapons.',
                       'Ability_hunter_camouflage.png']
    },
    "Mage": {
        "an Arcane": [0x3FC7EB, 'Ranged DPS', 'Manipulates the arcane, destroying enemies with overwhelming power.',
                      'Spell_holy_magicalsentry.png'],
        "a Fire": [0x3FC7EB, 'Ranged DPS', 'Ignites enemies with balls of fire and combustive flames.',
                   'Spell_fire_firebolt02.png'],
        "a Frost": [0x3FC7EB, 'Ranged DPS', 'Freezes enemies in their tracks and shatters them with Frost magic.',
                    'Spell_frost_frostbolt02.png']
    },
    "Monk": {
        "a Brewmaster": [0x00FF98, 'Tank',
                         'A sturdy brawler who uses liquid fortification and unpredictable movement to avoid damage and protect allies.',
                         'Spell_monk_brewmaster_spec.png'],
        "a Windwalker": [0x00FF98, 'Melee DPS', 'A martial artist without peer who pummels foes with hands and fists.',
                         'Spell_monk_windwalker_spec.png'],
        "a Mistweaver": [0x00FF98, 'Healer',
                         'A healer who mixes traditional herbal medicine with Pandaren martial arts.',
                         'Spell_monk_mistweaver_spec.png']
    },
    "Paladin": {
        "a Protection": [0xF48CBA, 'Tank',
                         'Uses Holy magic to shield <himself/herself> and defend allies from attackers.',
                         'Ability_paladin_shieldofthetemplar.png'],
        "a Holy": [0xF48CBA, 'Healer', 'Invokes the power of the Light to protect and to heal.',
                   'Spell_holy_holybolt.png'],
        "a Retribution": [0xF48CBA, 'Melee DPS',
                          'A righteous crusader who judges and punishes opponents with weapons and Holy magic.',
                          'Spell_holy_auraoflight.png']
    },
    "Priest": {
        "a Shadow": [0xFFFFFF, 'Ranged DPS',
                     'Uses sinister Shadow magic, especially damage-over-time spells, to eradicate enemies.',
                     'Spell_shadow_shadowwordpain.png'],
        "a Discipline": [0xFFFFFF, 'Healer',
                         'Uses magic to shield allies from taking damage as well as heal their wounds.',
                         'Spell_holy_powerwordshield.png'],
        "a Holy": [0xFFFFFF, 'Healer',
                   'A versatile healer who can reverse damage on individuals or groups and even heal from beyond the grave.',
                   'Spell_holy_guardianspirit.png']
    },
    "Rogue": {
        "an Assassination": [0xFFF468, 'Melee DPS',
                             'A deadly master of poisons who dispatches victims with vicious dagger strikes.',
                             'Ability_rogue_eviscerate.png'],
        "an Outlaw": [0xFFF468, 'Melee DPS',
                      'A swashbuckler who uses agility and guile to stand toe-to-toe with enemies.',
                      'Inv_sword_30.png'],
        "a Subtlety": [0xFFF468, 'Melee DPS',
                       'A dark stalker who leaps from the shadows to ambush <his/her> unsuspecting prey.',
                       'Ability_stealth.png']
    },
    "Shaman": {
        "an Elemental": [0x0070DD, 'Ranged DPS',
                         'A spellcaster who harnesses the destructive forces of nature and the elements.',
                         'Spell_nature_lightning.png'],
        "an Enhancement": [0x0070DD, 'Melee DPS',
                           'A totemic warrior who strikes foes with weapons imbued with elemental power.',
                           'Spell_shaman_improvedstormstrike.png'],
        "a Restoration": [0x0070DD, 'Healer',
                          'A healer who calls upon ancestral spirits and the cleansing power of water to mend allies\' wounds.',
                          'Spell_nature_magicimmunity.png']
    },
    "Warlock": {
        "an Affliction": [0x8788EE, 'Ranged DPS',
                          'A master of Shadow magic who specializes in drains and damage-over-time spells.',
                          'Spell_shadow_deathcoil.png'],
        "a Demonology": [0x8788EE, 'Ranged DPS',
                         'A master of demonic magic who transforms into a demon and compels demonic powers to aid him.',
                         'Spell_shadow_metamorphosis.png'],
        "a Destruction": [0x8788EE, 'Ranged DPS', 'A master of chaos who calls down fire to burn and demolish enemies.',
                          'Spell_shadow_rainoffire.png']
    },
    "Warrior": {
        "a Protection": [0xC69B6D, 'Tank',
                         'A stalwart protector who uses a shield to safeguard <himself/herself> and <his/her> allies.',
                         'Ability_warrior_defensivestance.png'],
        "an Arms": [0xC69B6D, 'Melee DPS',
                    'A battle-hardened master of two-handed weapons, using mobility and overpowering attacks to strike <his/her> opponents down.',
                    'Ability_warrior_savageblow.png'],
        "a Fury": [0xC69B6D, 'Melee DPS',
                   'A furious berserker wielding a weapon in each hand, unleashing a flurry of attacks to carve <his/her> opponents to pieces.',
                   'Ability_warrior_innerrage.png']
    }
}

wow_class_color_dict = {
    "Death Knight": 0xC41F3B,
    "Demon Hunter": 0xA330C9,
    "Druid": 0xFF7D0A,
    "Hunter": 0xAAD372,
    "Mage": 0x3FC7EB,
    "Monk": 0x00FF98,
    "Paladin": 0xF48CBA,
    "Priest": 0xFFFFFF,
    "Rogue": 0xFFF468,
    "Shaman": 0x0070DD,
    "Warlock": 0x8788EE,
    "Warrior": 0xC69B6D,
    "Evoker": 0x33937F
}
